force-app/main/default/objects/Account/recordTypes/Storeroom.recordType-meta.xml
<RecordType>
    <fullName>Storeroom</fullName>
    <active>true</active>
    <description>Internal Storeroom</description>
    <label>Storeroom</label>
</RecordType>

force-app/main/default/objects/User/fields/Manages_Brand__c.field-meta.xml
<CustomField>
    <fullName>Manages_Brand__c</fullName>
    <label>Manages Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BF_Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BF_Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Agency Brands</fullName>
    </customValue>
    <customValue>
        <fullName>BenRiach</fullName>
    </customValue>
    <customValue>
        <fullName>Chambord</fullName>
    </customValue>
    <customValue>
        <fullName>Collingwood Canadian</fullName>
    </customValue>
    <customValue>
        <fullName>EJ RTS</fullName>
    </customValue>
    <customValue>
        <fullName>El Jimador</fullName>
    </customValue>
    <customValue>
        <fullName>El Jimador RTD</fullName>
    </customValue>
    <customValue>
        <fullName>Finlandia Vodka</fullName>
    </customValue>
    <customValue>
        <fullName>Gentleman Jack</fullName>
    </customValue>
    <customValue>
        <fullName>GJ &amp; Cola</fullName>
    </customValue>
    <customValue>
        <fullName>GlenDronach</fullName>
    </customValue>
    <customValue>
        <fullName>Glenglassaugh</fullName>
    </customValue>
    <customValue>
        <fullName>Herradura</fullName>
    </customValue>
    <customValue>
        <fullName>Herradura Seleccion Suprema</fullName>
    </customValue>
    <customValue>
        <fullName>Heradura Ultra</fullName>
    </customValue>
    <customValue>
        <fullName>Jack Daniel&#39;s</fullName>
    </customValue>
    <customValue>
        <fullName>Jack Daniel&#39;s Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Jack Daniel&#39;s Honey</fullName>
    </customValue>
    <customValue>
        <fullName>Jagermeister</fullName>
    </customValue>
    <customValue>
        <fullName>JD &amp; Cola</fullName>
    </customValue>
    <customValue>
        <fullName>JD 1907</fullName>
    </customValue>
    <customValue>
        <fullName>JD 1907 RTD</fullName>
    </customValue>
    <customValue>
        <fullName>JD American Serve</fullName>
    </customValue>
    <customValue>
        <fullName>JD Craft Rye</fullName>
    </customValue>
    <customValue>
        <fullName>JD RTD</fullName>
    </customValue>
    <customValue>
        <fullName>JD Sinatra</fullName>
    </customValue>
    <customValue>
        <fullName>JD Single Barrel</fullName>
    </customValue>
    <customValue>
        <fullName>JD Tennessee Fire</fullName>
    </customValue>
    <customValue>
        <fullName>JD Tennessee Rye</fullName>
    </customValue>
    <customValue>
        <fullName>JD Winter Jack</fullName>
    </customValue>
    <masterLabel>BF Brands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/sendNotificationsToGroup_Test.cls
@isTest(SeeAllData=true)
private class sendNotificationsToGroup_Test {
    static testMethod void unitTest1() {
        INFW_TestHelper helper = new INFW_TestHelper();
        
        Map<String, RecordTypeInfo> aRecordTypes = Schema.SObjectType.Account.getRecordTypeInfosByName();

        String rtAUAccount = aRecordTypes.get('AUD - Outlet').getRecordTypeId();
        String rtStoreroom = aRecordTypes.get('Storeroom').getRecordTypeId();
               
        /*
        User user1 = helper.createUser('System Administrator', 'Test', 'Tsakiridis', '');
        user1.Market__c = 'Australia';
        user1.Manages_Brand__c = 'Gentleman Jack';
        user1.Email = 'tass_tsakiridis@b-f.com';
        insert user1;
        */
        Group group1 = new Group();
        group1.Name = 'TestGroup';
        group1.DeveloperName = 'Test_Group';
        insert group1;
        
        GroupMember member1 = new GroupMember();
        member1.GroupId = group1.Id;
        member1.UserOrGroupId = UserInfo.getUserId();
        insert member1;        
            
        System.runAs(new User(Id = UserInfo.getUserId())) {
            Account account1 = new Account();
            account1.RecordTypeId = rtStoreroom;
            account1.Name = 'Test Account';    
            insert account1;

            AccountShare aShare = new AccountShare();
            aShare.AccountId = account1.Id;
            aShare.AccountAccessLevel = 'Edit';
            aShare.OpportunityAccessLevel = 'Read';
            aShare.RowCause = 'manual';
            aShare.UserOrGroupId = group1.Id;
            insert aShare;
            
            List<String> accountIds = new List<String>{account1.Id};
                
            List<sendNotificationsToGroup.sendNotificationsToGroupParams> params = new List<sendNotificationsToGroup.sendNotificationsToGroupParams>();
            sendNotificationsToGroup.sendNotificationsToGroupParams param = new sendNotificationsToGroup.sendNotificationsToGroupParams();
            params.add(param);

            List<sendNotificationsToGroup.sendNotificationsToGroupResults> results = sendNotificationsToGroup.sendNotificationsToGroup(params);
            
            param.recordIds = accountIds;
            params.clear();
            params.add(param);

            results = sendNotificationsToGroup.sendNotificationsToGroup(params);

            param.recordIds = accountIds;
            param.emailTemplateName = 'AU_Sample_Order_Submitter_Notification';
            params.clear();
            params.add(param);

            results = sendNotificationsToGroup.sendNotificationsToGroup(params);
            
            param.objectApiName = 'Account';
            param.includeGroups = false;
            param.onlyNotifyOwner = true;
            param.userOrGroup = '';
            param.userOrGroupName = '';
            params.add(param);
            
			results = sendNotificationsToGroup.sendNotificationsToGroup(params);
            
            param.includeGroups = true;
            param.onlyNotifyOwner = false;
            param.userOrGroup = 'Group';
            param.userOrGroupName = 'TestGroup';
            params.clear();
            params.add(param);
            results = sendNotificationsToGroup.sendNotificationsToGroup(params);
        }
    }
}