force-app/main/default/objects/SAP_Interfaced_Data__c/SAP_Interfaced_Data__c.object-meta.xml
<CustomObject>
    <label>SAP Interfaced Data</label>
    <nameField>
        <displayFormat>SAPID-{0}</displayFormat>
        <label>SAP Interfaced Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Interfaced Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Manager Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Authorised_By__c.field-meta.xml
<CustomField>
    <fullName>Authorised_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorised By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SAP_Interfaced_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Authorised_Date__c.field-meta.xml
<CustomField>
    <fullName>Authorised_Date__c</fullName>
    <label>Authorised Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Business_City__c.field-meta.xml
<CustomField>
    <fullName>Business_City__c</fullName>
    <label>Business City</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Business_Country__c.field-meta.xml
<CustomField>
    <fullName>Business_Country__c</fullName>
    <label>Business Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Business_Postcode__c.field-meta.xml
<CustomField>
    <fullName>Business_Postcode__c</fullName>
    <label>Business Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Business_State__c.field-meta.xml
<CustomField>
    <fullName>Business_State__c</fullName>
    <label>Business State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACT</fullName>
            </value>
            <value>
                <fullName>NSW</fullName>
            </value>
            <value>
                <fullName>NT</fullName>
            </value>
            <value>
                <fullName>QLD</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>VIC</fullName>
            </value>
            <value>
                <fullName>WA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account events</fullName>
            </value>
            <value>
                <fullName>Activities to consumers</fullName>
            </value>
            <value>
                <fullName>AU1-Samples for Marketing Related Activities</fullName>
            </value>
            <value>
                <fullName>AU2-Samples for Sales Related Activities</fullName>
            </value>
            <value>
                <fullName>AU3-Duty Free Samples</fullName>
            </value>
            <value>
                <fullName>AU4-Discount Sample Orders</fullName>
            </value>
            <value>
                <fullName>AU5-Samples for Admin Activities</fullName>
            </value>
            <value>
                <fullName>AU6-Ecomm Sample Orders</fullName>
            </value>
            <value>
                <fullName>Discount Sample Orders</fullName>
                <isActive>false</isActive>
                <label>Discount Sample Orders</label>
            </value>
            <value>
                <fullName>Duty Free Samples</fullName>
                <isActive>false</isActive>
                <label>Duty Free Samples</label>
            </value>
            <value>
                <fullName>EFG</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Exhibits</fullName>
            </value>
            <value>
                <fullName>External Relationship</fullName>
            </value>
            <value>
                <fullName>Internal Activity</fullName>
            </value>
            <value>
                <fullName>Marketing Activity</fullName>
            </value>
            <value>
                <fullName>PR Activity</fullName>
                <isActive>false</isActive>
                <label>PR Activity</label>
            </value>
            <value>
                <fullName>Product Promotion</fullName>
                <isActive>false</isActive>
                <label>Product Promotion</label>
            </value>
            <value>
                <fullName>Sample - Ad</fullName>
            </value>
            <value>
                <fullName>Sample - Display at account</fullName>
            </value>
            <value>
                <fullName>Sample - Inspection</fullName>
            </value>
            <value>
                <fullName>Sample - Research</fullName>
            </value>
            <value>
                <fullName>Samples for Admin Activities</fullName>
                <isActive>false</isActive>
                <label>Samples for Admin Activities</label>
            </value>
            <value>
                <fullName>Samples for Marketing Related Activities</fullName>
                <isActive>false</isActive>
                <label>Samples for Marketing Related Activities</label>
            </value>
            <value>
                <fullName>Samples for Sales Related Activities</fullName>
                <isActive>false</isActive>
                <label>Samples for Sales Related Activities</label>
            </value>
            <value>
                <fullName>SD0 - Sample Orders for Customers (Branded promotional materials &amp; displays)</fullName>
            </value>
            <value>
                <fullName>SD0-Samples for Customers</fullName>
                <isActive>false</isActive>
                <label>SD0-Samples for Customers</label>
            </value>
            <value>
                <fullName>SD0 - Tasting and sampling events whether at customer’s location or general location</fullName>
            </value>
            <value>
                <fullName>SD5-Samples</fullName>
                <isActive>false</isActive>
                <label>SD5-Samples</label>
            </value>
            <value>
                <fullName>SD5 - Samples for office display, business meeting consumption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Finance_Authorised_By__c.field-meta.xml
<CustomField>
    <fullName>Finance_Authorised_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Authorised By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SAP_Interfaced_Data_FinanceAuthorised</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Finance_Authorised_Date__c.field-meta.xml
<CustomField>
    <fullName>Finance_Authorised_Date__c</fullName>
    <label>Finance Authorised Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Is_International_Order__c.field-meta.xml
<CustomField>
    <fullName>Is_International_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is International Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market</label>
    <referenceTo>Market__c</referenceTo>
    <relationshipLabel>SAP Interfaced Data</relationshipLabel>
    <relationshipName>SAP_Interfaced_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <formula>CreatedBy.FederationIdentifier + &#39;-&#39; + TEXT(YEAR(Requested_Delivery_Date__c)) + RIGHT(&#39;00&#39;+TEXT(MONTH(Requested_Delivery_Date__c)),2) + RIGHT(&#39;00&#39;+TEXT(DAY(Requested_Delivery_Date__c)),2) + RIGHT(&#39;00&#39;+TEXT(HOUR(TIMEVALUE(CreatedDate))),2) + RIGHT(&#39;00&#39;+TEXT(MINUTE(TIMEVALUE(CreatedDate))),2)</formula>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data__c/fields/Requested_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Date__c</fullName>
    <defaultValue>TODAY() + 1</defaultValue>
    <label>Requested Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data_Item__c/SAP_Interfaced_Data_Item__c.object-meta.xml
<CustomObject>
    <label>SAP Interfaced Data Item</label>
    <nameField>
        <displayFormat>SAPDI-{0}</displayFormat>
        <label>SAP Interfaced Data Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAP Interfaced Data Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Interfaced_Data_Item__c/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <formula>Product__r.Brand_Name__c</formula>
    <label>Brand Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data_Item__c/fields/Pack_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Pack_Quantity__c</fullName>
    <formula>Product__r.Pack_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pack Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>SAP Interfaced Data Items</relationshipLabel>
    <relationshipName>SAP_Interfaced_Data_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data_Item__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <formula>Product__r.ProductCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Interfaced_Data_Item__c/fields/SAP_Interfaced_Data__c.field-meta.xml
<CustomField>
    <fullName>SAP_Interfaced_Data__c</fullName>
    <label>SAP Interfaced Data</label>
    <referenceTo>SAP_Interfaced_Data__c</referenceTo>
    <relationshipLabel>SAP Interfaced Data Items</relationshipLabel>
    <relationshipName>SAP_Interfaced_Data_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SampleOrder_Controller.cls
public with sharing class SampleOrder_Controller {

    @AuraEnabled
    public static User getCurrentUserInfo() {
    	User u = [SELECT Id, Name, Market__c FROM User WHERE Id =:UserInfo.getUserId()];
        return u;
    }
    
	@AuraEnabled
	public static String getUIThemeDescription() {
		String theme = UserInfo.getUiThemeDisplayed();
		return theme;
	}
    
    @AuraEnabled
    public static bfObjectDescribe getObjectDetails() {
        system.debug('[SampleOrder_Controller.getObjectDetails]');
        bfObjectDescribe obj = new bfObjectDescribe('SAP_Interfaced_Data__c');
        obj.getDescribe(true, true, true);
        return obj;
    }
    
    @AuraEnabled
    public static List<SAP_Interfaced_Data__c> getSampleOrders() {
        System.debug('current user: ' + UserInfo.getLastName() + ', ' + UserInfo.getFirstName() + ', ' + UserInfo.getUserId());
    	return Sample_Order_Helper.getSampleOrders();
    }
    
    @AuraEnabled
    public static SAP_Interfaced_Data__c getSampleOrder(String recordId) {
        if (recordId == null || recordId == '') { return null; }
        return [SELECT Id, Name, Order_Number__c, Approval_Status__c, Requested_Delivery_Date__c, Authorised_By__c, Authorised_By__r.Name, Authorised_Date__c, Finance_Authorised_By__c, Finance_Authorised_Date__c, Classification__c, Business_Name__c, Business_Address__c, Business_City__c, Business_State__c, Business_Postcode__c, Business_Country__c, Contact_Name__c, Contact_Phone__c, Reason__c, Is_International_Order__c, (SELECT Id, Name, SAP_Interfaced_Data__c, Product__c, Brand_Name__c, Product_Code__c, Quantity__c FROM SAP_Interfaced_Data_Items__r) FROM SAP_Interfaced_Data__c WHERE Id=:recordId];
    }
    
    @AuraEnabled
    public static SAP_Interfaced_Data__c saveSampleOrder(SAP_Interfaced_Data__c theSampleOrder) {
        if (theSampleOrder != null) {
            Market__c market = [SELECT Id FROM Market__c WHERE Country_ISO_Code_2__c =:theSampleOrder.Business_Country__c LIMIT 1];
            if (market != null) {
                theSampleOrder.Market__c = market.Id;
            }
            upsert theSampleOrder;
        }
        
        return theSampleOrder;
    }
    
    @AuraEnabled
    public static List<SampleOrderItem> saveOrderItems(String sapId, String sapItems) {
        if (sapId == null || sapId == '') { return null; }
        if (sapItems == null || sapItems.length() == 0) { return null; }
        
        Map<String, RecordTypeInfo> rtList = SAP_Interfaced_Data_Item__c.SObjectType.getDescribe().getRecordTypeInfosByName();
        String rtSampleOrder = rtList.get('Sample Order').getRecordTypeId();
        
        System.debug('sapId: ' + sapId);
        List<SAP_Interfaced_Data_Item__c> l_SAPItems = new List<SAP_Interfaced_Data_Item__c>();
        List<SampleOrderItem> items = (List<SampleOrderItem>)System.JSON.deserializeStrict(sapItems, List<SampleOrderItem>.Class);
        System.debug('# of items to save: ' + items.size());
        SAP_Interfaced_Data_Item__c sapItem;
        try {
            for(SampleOrderItem s : items) {
                System.debug('items.key id: ' + s.id + ', product: ' + s.productId);
            }
            
            for(SampleOrderItem i : items) {
                sapItem = new SAP_Interfaced_Data_Item__c();
                sapItem.RecordTypeId = rtSampleOrder;
                sapItem.SAP_Interfaced_Data__c = sapId;
                sapItem.Product__c = i.productId;
                sapItem.Quantity__c = i.quantity;
                if(i.id != i.productId && i.id != '') {
                    sapItem.Id = i.Id;
                }
                l_SAPItems.add(sapItem);
            }
        } catch(Exception ex) {
            System.debug('exception: ' + ex.getMessage());
        }     
        
        upsert l_SAPItems;
        for(SAP_Interfaced_Data_Item__c i : l_SAPItems) {
            for(SampleOrderItem soi : items) {
                if (soi.productId == i.Product__c) {
                    soi.Id = i.Id; break;
                }
            }
        }
        
        return items;
    }

	@AuraEnabled
    public static SAP_Interfaced_Data__c getInterfacedData(String sapId) {
        if (sapId == null || sapId.length() == 0) { return null; }
        
        SAP_Interfaced_Data__c sap = [SELECT Id, Name, Requested_Delivery_Date__c, Classification__c, Business_Name__c, Business_Address__c, Business_City__c, Business_State__c, Business_Country__c, Contact_Name__c, Contact_Phone__c, Reason__c, (SELECT Id, Name, Product__c, SAP_Interfaced_Data__c, Brand_Name__c, Product_Code__c FROM SAP_Interfaced_Data_Items__r) FROM SAP_Interfaced_Data__c WHERE Id =:sapId];
        return sap;
    }   
    
    @AuraEnabled
    public static List<SampleOrderItem> getProducts(String sapId) {        
		Market__c market;
        User u = getCurrentUserInfo();
        if (u != null) {
            market = [SELECT Id, Name FROM Market__c WHERE Name =:u.Market__c];
        }
        if (market == null) {
            market = [SELECT Id, Name FROM Market__c WHERE Name = 'Australia'];
        }
        
        Boolean found = false;
        List<Product__c> products = [SELECT Id, Name, Brand__c, Brand_Name__c, Pack_Quantity__c FROM Product__c WHERE IsActive__c = true AND Market__c=:market.Id AND Used_For__c INCLUDES ('Sample Order')];
        
        List<SampleOrderItem> items = new List<SampleOrderItem>();
        for(Product__c p : products) {
            items.add(new SampleOrderItem('', p.Id, p.Name, p.Brand_Name__c, (Integer)p.Pack_Quantity__c, 0));
        }
        return items;
    }
    
    @AuraEnabled
    public static void submitForApproval(String sapId) {
        System.debug('sapId: ' + sapId);
        if (sapId != null && sapId.length() > 0) {            
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setObjectId(sapId);
            Approval.ProcessResult result = Approval.process(req1);
        }
        
    }
}